services:
  das:
    build: .
    container_name: calculadora-das
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      APP_NAME: "dasfssdevcombr"
      APP_ENV: local
      APP_KEY: "base64:sAohvTPVoS6tT+MJUcUzzWSNiB6IgFjJN0HUTZSCNrg="
      APP_DEBUG: "true"
      APP_URL: "https://das.fssdev.com.br"
      SESSION_DRIVER: file
      SESSION_LIFETIME: "120"
      CACHE_STORE: file
      LOG_CHANNEL: stderr
      LOG_LEVEL: error
    volumes:
      - ./storage:/var/www/html/storage
