services:
  das:
    build: .
    container_name: calculadora-das
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      APP_NAME: "Calculadora DAS"
      APP_ENV: local
      APP_KEY: "base64:9HqVGgKVWw0yoV1WtwsPsHqgK4qoAYxUFhEhCbj204o="
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8080"
      DB_CONNECTION: sqlite
      DB_DATABASE: "/var/www/html/storage/app/database.sqlite"
      SESSION_DRIVER: file
      SESSION_LIFETIME: "120"
      CACHE_STORE: file
      LOG_CHANNEL: stderr
      LOG_LEVEL: error
    volumes:
      - das_storage:/var/www/html/storage

volumes:
  das_storage:
    driver: local
